name: social-media-app
channels:
  - defaults
  - conda-forge
  - fastai
  - r
  - bioconda
dependencies:
  - pip=23.3.1
  - python=3.12.1
  - pip:
      - aniso8601==9.0.1
      - asgiref==3.7.2
      - django==5.0.3
      - graphene==3.3
      - graphene-django==3.2.0
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - promise==2.3
      - redis==5.0.3
      - six==1.16.0
      - sqlparse==0.4.4
      - text-unidecode==1.3
      - gunicorn==21.2.0
